# Generated by Django 4.2.4 on 2023-09-07 13:55

import chat.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='chat',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chat',
            name='id',
            field=models.CharField(
                db_index=True,
                default=chat.models.hex_uuid,
                editable=False,
                max_length=32,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='userchat',
            name='user',
            field=models.PositiveIntegerField(),
        ),
    ]
