# Generated by Django 4.2.4 on 2023-09-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('chat', '0002_alter_chat_options_chat_created_alter_chat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.JSONField(default=dict),
        ),
    ]
