# Generated by Django 4.2.4 on 2023-09-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('chat', '0003_alter_chat_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created']},
        ),
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
