# Generated by Django 4.2.4 on 2023-10-02 14:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('chat', '0004_alter_message_options_alter_message_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created']},
        ),
    ]
