# Generated by Django 4.2.4 on 2023-11-03 18:49

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('chat', '0005_alter_message_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=chat.models.file_message_upload_path),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
    ]
